[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --include=optional --no-audit",
  "npm rebuild"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
