[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required for server'"]

[start]
cmd = "cd server && npm start"
