[build]
builder = "nixpacks"
buildCommand = "cd server && npm ci --only=production"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"
